name: DevOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Script
        run: echo "CI/CD Pipeline Working Successfully"
            - name: List Files
      run: ls -la
